version: '3.1'

services:

  web:
    build:
      context: .
      target: install-deps
      args:
        - NODE_ENV=development
    command: ["npm", "run", "dev"]
    ports:
      - 10000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./.eslintrc.json:/app/.eslintrc.json
      # bind mount the certs to avoid any chance of them ending up in built image
      - ./dev-server.key:/app/dev-server.key
      - ./dev-server.pem:/app/dev-server.pem
    environment:
      API_URL: http://host.docker.internal:10001
      PORT: 3000
